CREATE TABLE CLOCK_ADPEMP (
 	EMPLOYEE_ID VARCHAR(15) NOT NULL,
	ASSOC_ID VARCHAR(20) NOT NULL,
	POSITION_ID VARCHAR(20) NOT NULL
);


CREATE TABLE CLOCK_ENTRY (
 	EMPLOYEE_ID VARCHAR(15) NOT NULL,
	LAST_CLOCK_IN DATETIME,
	LAST_CLOCKOUT DATETIME	
);


INSERT INTO CLOCK_ADPEMP (EMPLOYEE_ID, ASSOC_ID, POSITION_ID) VALUES ('Id1','A1','P1');
INSERT INTO CLOCK_ADPEMP (EMPLOYEE_ID, ASSOC_ID, POSITION_ID) VALUES ('Id2','A2','P2');
INSERT INTO CLOCK_ADPEMP (EMPLOYEE_ID, ASSOC_ID, POSITION_ID) VALUES ('Id3','A3','P3');


SELECT EMPLOYEE_ID, ASSOC_ID, POSITION_ID FROM CLOCK_ADEMP;

